/// Contexto sociodemográfico agregado dos bairros de Santos com base no Censo Demográfico 2022.
table Bairros

	measure População = SUM(Bairros['População Total'])
		formatString: #,##0

	column 'Código do Bairro'
		dataType: string
		isHidden
		summarizeBy: none
		sourceColumn: cd_bairro

	column Bairro
		dataType: string
		summarizeBy: none
		sourceColumn: bairro

	column Localização
		dataType: string
		summarizeBy: none
		sourceColumn: localizacao

	column 'Área km²'
		dataType: decimal
		summarizeBy: none
		sourceColumn: area_km2

	column 'População Total'
		dataType: int64
		summarizeBy: sum
		sourceColumn: populacao_total

	column 'População Demografia'
		dataType: int64
		isHidden
		summarizeBy: sum
		sourceColumn: populacao_demografia

	column 'Idade 0–14'
		dataType: int64
		summarizeBy: sum
		sourceColumn: idade_0_14

	column 'Idade 15–29'
		dataType: int64
		summarizeBy: sum
		sourceColumn: idade_15_29

	column 'Idade 30–59'
		dataType: int64
		summarizeBy: sum
		sourceColumn: idade_30_59

	column 'Idade 60+'
		dataType: int64
		summarizeBy: sum
		sourceColumn: idade_60_mais

	column 'População Idade Classificada'
		dataType: int64
		isHidden
		summarizeBy: sum
		sourceColumn: populacao_idade_classificada

	column 'População 15+ Alfabetização'
		dataType: int64
		isHidden
		summarizeBy: sum
		sourceColumn: populacao_15_mais_alfabetizacao

	column 'Alfabetizados 15+'
		dataType: int64
		isHidden
		summarizeBy: sum
		sourceColumn: alfabetizados_15_mais

	column 'Taxa Alfabetização 15+'
		dataType: decimal
		summarizeBy: none
		sourceColumn: taxa_alfabetizacao_15_mais_pct

	column 'Responsáveis DPP Ocupados'
		dataType: int64
		isHidden
		summarizeBy: sum
		sourceColumn: responsaveis_dpp_ocupados

	column 'Renda Média do Responsável'
		dataType: decimal
		summarizeBy: none
		sourceColumn: renda_responsavel_media

	column 'Renda Mediana do Responsável'
		dataType: decimal
		summarizeBy: none
		sourceColumn: renda_responsavel_mediana

	column 'Renda Disponível'
		dataType: boolean
		isHidden
		summarizeBy: none
		sourceColumn: renda_disponivel

	partition Bairros = m
		mode: import
		source =
			let
				Fonte = Json.Document(
					Web.Contents(
						"https://biblio-webapi.onrender.com",
						[
							RelativePath = "gestor/analytics/powerbi/",
							Headers = [Accept = "application/json"],
							Timeout = #duration(0, 0, 2, 0)
						]
					)
				),
				Registros = Fonte[dim_bairro],
				Tabela = Table.FromRecords(Registros),
				Tipos = Table.TransformColumnTypes(
					Tabela,
					{
						{"cd_bairro", type text},
						{"bairro", type text},
						{"area_km2", type number},
						{"populacao_total", Int64.Type},
						{"populacao_demografia", Int64.Type},
						{"idade_0_14", Int64.Type},
						{"idade_15_29", Int64.Type},
						{"idade_30_59", Int64.Type},
						{"idade_60_mais", Int64.Type},
						{"populacao_idade_classificada", Int64.Type},
						{"populacao_15_mais_alfabetizacao", Int64.Type},
						{"alfabetizados_15_mais", Int64.Type},
						{"taxa_alfabetizacao_15_mais_pct", type number},
						{"responsaveis_dpp_ocupados", Int64.Type},
						{"renda_responsavel_media", type number},
						{"renda_responsavel_mediana", type number},
						{"renda_disponivel", type logical}
					},
					"pt-BR"
				),
				ComLocalizacao = Table.AddColumn(
					Tipos,
					"localizacao",
					each [bairro] & ", Santos, SP, Brasil",
					type text
				)
			in
				ComLocalizacao
