# Generated by Django 5.2 on 2026-04-25 13:52

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestor', '0011_usuario'),
    ]

    operations = [
        migrations.CreateModel(
            name='Emprestimo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_emprestimo', models.DateField(default=django.utils.timezone.localdate)),
                ('data_prevista_devolucao', models.DateField(blank=True, null=True)),
                ('data_devolucao', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('aberto', 'Aberto'), ('devolvido', 'Devolvido')], default='aberto', max_length=20)),
                ('observacoes', models.TextField(blank=True, null=True)),
                ('livro', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestor.livro')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestor.usuario')),
            ],
            options={
                'ordering': ['-data_emprestimo', '-id'],
            },
        ),
    ]
