# Generated by Django 5.2 on 2026-04-25 13:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestor', '0012_emprestimo'),
    ]

    operations = [
        migrations.AddField(
            model_name='emprestimo',
            name='unidade',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='gestor.unidade'),
        ),
    ]
